### ISSUE TITLE
Complete Dataset Availability

### ISSUE THREAD

**Issue by DahTach** [ramajoballester/UC3M-LP#1]
Hi, I wanted to use the UC3M-LP dataset for a ml project for European license plates detection. I read it's an open source license plate dataset but I cannot find any link to the complete dataset. In the readme I saw a Waiting for Acceptance comment and so I wanted to know if the full dataset will ever be available and if so indicatively when. Thanks

**Comment by ramajoballester** [comment]
Hi, @DahTach!
Sorry for the late reply. The paper has just been published so the download link is now available.
