### ISSUE TITLE
BGR and RGB images in the dataset

### ISSUE THREAD

**Issue by danigarciaoca** [ramajoballester/UC3M-LP#3]
Hi,

First of all thanks for this work, it's great :smile:. I have a question related to the dataset. I saw that most of the images are BGR-saved but some of them ar RGB. Should them be read as BGR or RGB when training a model? What is the purpose of this mixed-saving? To have more diversity (kind of image augmentation)?

Some examples: 
![00088](https://github.com/user-attachments/assets/17214b66-d27b-4bb3-8cd7-f9660e8d3d79)
![00089](https://github.com/user-attachments/assets/2dc20059-59cd-4403-8629-2e399bc7b1ce)
Thanks!

**Comment by ramajoballester** [comment]
Hi, @danigarciaoca.

Thanks for your kind words! 
As it was discussed in section 4 in the [paper](https://doi.org/10.1016/j.robot.2023.104608): "The treatment and publication of images that contain personal information is not straight-forward, so a particular emphasis was placed on implementing robust protocols and procedures to meticulously anonymize the data, thereby eliminating any potential traces of personally identifiable information. These efforts were aimed at safeguarding the privacy and anonymity of individuals whose data was included in the dataset, and will be described in Sections 4.1 and 4.2."

Apart from blurring two characters per license plate, adding color noise makes it a bit more difficult to extract personal information from the vehicles. This was the least invasive procedure from all the possibilities considered, given that it is also a technique commonly used for data augmentation.

**Comment by danigarciaoca** [comment]
Got it! I'll take a read to that section. Many thanks
